### ISSUE TITLE
Request for file save with out user credentials?

### ISSUE THREAD

**Issue by NareshReddyG** [microsoftgraph/angular-excelstarter-sample#1]
Is there any working example for the file upload to onedrive from angular4, without forcing the end user to enter the onedrive/microsoft account credentials?

**Comment by jamescro** [comment]
It's not in JavaScript, but this sample shows the REST queries necessary to upload an Excel file programmatically.

https://github.com/microsoftgraph/aspnet-todo-rest-sample

**Comment by jamescro** [comment]
Closing for now. Please let me know if you have any other questions about REST + Excel files.
